<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBrb1gzi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBrb1gzi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBrb1gzi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBrb1gzi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBrb1gzi\appProdProjectContainer([
    'container.build_hash' => 'Brb1gzi',
    'container.build_id' => '8b8b54ea',
    'container.build_time' => 1591936470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBrb1gzi');
